version: "3.8"

volumes:
    sql-server:

services:     
    sql-server:
        image: "mcr.microsoft.com/mssql/server:2017-latest"
        container_name: graphql-sample-db
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=sa@@2020
        ports:
            - "1433:1433"
        volumes: 
            - sql-server:/var/opt/mssql

    graphql-sample:
        image: graphql-sample
        container_name: graphql-sample
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
          - "8080:80"
        depends_on:
          - sql-server